import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { providers, type Role } from '../domain';
import { setRole, useDemoState } from '../store';
import { Empty, Icon, Meta, PageIntro, ProviderGrid } from '../components';
export function Messages() { const [text, setText] = useState(''); const [sent, setSent] = useState<string[]>([]); return <><Meta title="Messages" description="Keep provider conversations connected to their job request."/><PageIntro eyebrow="Job communication" title="Messages" description="Example conversation for NX-DEMO-1048. Messages stay on this page and are not sent to another person."/><section className="section body-section"><div className="chat-demo"><div className="chat-context"><b>Generator servicing</b><small>Ikeja, Lagos · NX-DEMO-1048</small><Link to="/jobs/NX-DEMO-1048">View job <Icon name="arrow"/></Link></div><div className="chat-thread"><p className="chat-date">Example conversation</p><div className="bubble bubble-other">Can you share the generator model and the last service date?</div><div className="bubble bubble-own">It is a 5.5kVA unit. Last serviced around June.</div>{sent.map((m, i) => <div className="bubble bubble-own" key={i}>{m}</div>)}</div><form className="chat-compose" onSubmit={(e) => { e.preventDefault(); if (text.trim()) { setSent([...sent, text.trim()]); setText(''); } }}><label className="sr-only" htmlFor="message">Write a message</label><input id="message" value={text} onChange={(e) => setText(e.target.value)} placeholder="Write a demo message"/><button className="button button-dark">Add locally</button></form></div></section></>; }


export function Account() { const state = useDemoState(); return <><Meta title="Account" description="Access your Nexthub requests, saved providers and workspace."/><PageIntro eyebrow="Your account · Demo" title="Choose a workspace." description="Sign-in is not connected; select a demo view to inspect the interface."/><section className="section body-section"><div className="role-switch">{(['Customer', 'Provider', 'Business', 'Admin'] as Role[]).map((role) => <button className={state.role === role ? 'role-active' : ''} onClick={() => setRole(role)} key={role}>{role} view</button>)}</div><div className="account-grid">{[['My jobs', '/jobs'], ['Saved providers', '/saved'], ['Messages', '/messages'], ['Payments', '/payments'], ['Provider workspace', '/provider'], ['Business workspace', '/business'], ['Admin preview', '/admin'], ['Settings', '/settings']].map(([label, href]) => <Link to={href} className="account-card" key={href}><b>{label}</b><span>Open section <Icon name="arrow"/></span></Link>)}</div><p className="small-note">Authentication, password reset and protected account data need Supabase Auth and server-side access rules.</p></section></>; }

export function Saved() { const state = useDemoState(); const list = providers.filter((p) => state.saved.includes(p.id)); return <><Meta title="Saved providers" description="Compare provider profiles saved to this browser."/><PageIntro eyebrow="Your shortlist" title="Saved providers" description="Profiles saved in this browser demo."/><section className="section body-section"><ProviderGrid list={list}/>{list.length === 0 && <Empty title="No saved providers" text="Save a profile while you compare your options." link="/providers" label="Browse providers"/>}</section></>; }

export function Settings() { return <><Meta title="Account settings" description="Account notification and privacy settings preview."/><PageIntro eyebrow="Account settings" title="Settings" description="Account details and privacy preferences will appear here after sign-in is connected."/><section className="section body-section"><div className="notice">Settings cannot be saved to an authenticated account in this demo.</div></section></>; }

export function Payments() { return <><Meta title="Payments" description="Nexthub transaction and payment lifecycle information."/><PageIntro eyebrow="Payments · Not connected" title="Payment setup is not available yet." description="Nexthub has no payment gateway credentials or server-side payment functions configured in this project."/><section className="section body-section"><div className="payment-explain"><h2>What a safe payment flow needs</h2><ol><li>A server-created transaction for the accepted quote.</li><li>A signed gateway callback verified on the server.</li><li>An allocation tied to the job and recorded platform fee.</li><li>A separately approved settlement, payout or refund.</li></ol><div className="notice">No payment has been collected. Do not send funds to a provider based on this demo screen.</div></div></section></>; }

export function Notifications() { return <><Meta title="Notifications" description="Marketplace notifications preview."/><PageIntro eyebrow="Updates" title="Notifications" description="Notifications are generated from job events in the live product."/><section className="section body-section"><Empty title="No live notifications" text="New quotes, schedule changes and completion requests will show here after account and notification services are connected."/></section></>; }

export function Reviews() { return <><Meta title="Reviews" description="Customer reviews tied to completed Nexthub jobs."/><PageIntro eyebrow="Job feedback" title="Reviews belong to completed work." description="Only the customer on a completed job should be able to leave its review."/><section className="section body-section"><div className="notice">There are no job-backed reviews in this demo. Example reviews from the previous prototype were removed.</div></section></>; }

export function Login() { const { pathname } = useLocation(); const title = pathname === '/sign-up' ? 'Account creation is not connected.' : pathname === '/reset-password' ? 'Password recovery is not connected.' : 'Sign-in is not connected.'; const eyebrow = pathname === '/sign-up' ? 'Create an account' : pathname === '/reset-password' ? 'Recover an account' : 'Account access'; return <><Meta title={eyebrow} description={`${title} Account access is a preview until authentication is configured.`}/><section className="section body-section"><div className="auth-message"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>This frontend has no authentication service or account database configured. The demo role switch lets you preview each workspace without collecting a password.</p><Link className="button button-dark" to="/account">Choose a demo workspace</Link></div></section></>; }
