import { useMemo, useState, type FormEvent } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { categories, providers, type Provider } from '../domain';
import { proposeService, toggleSaved, useDemoState } from '../store';
import { Icon, Meta, NotFound, PageIntro, ProviderGrid, SearchBox } from '../components';
export function Home() {
  return <><Meta title="Find local services and independent professionals" description="Search services and providers across Nigeria, compare details, or post a task for quotes." indexable/>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">Find services across Nigeria</p><h1>Good work starts<br/>with the <em>right person.</em></h1><p className="hero-lead">From a leaking tap to a new website, look through local providers or describe the work and ask for quotes.</p><SearchBox/></div><aside className="hero-note"><div className="note-top"><span className="note-mark">N</span><span>Made for how work gets done here</span></div><div className="note-rule"/><p>Home repairs. Errands. Freelance work. Business services.</p><small>One place to explain the job, agree the scope and keep updates together.</small><Link className="text-link" to="/post-a-task">How a request works <Icon name="arrow"/></Link></aside></section>
    <section className="section category-section"><div className="section-top"><div><p className="eyebrow">Start with a service</p><h2>What needs doing?</h2></div><Link className="text-link" to="/services">All service categories <Icon name="arrow"/></Link></div><div className="category-grid">{categories.slice(0, 8).map((category, i) => <Link className="category-tile" to={`/services/${category.id}`} key={category.id}><span className="category-index">0{i + 1}</span><b>{category.name}</b><span className="category-arrow"><Icon name="arrow"/></span></Link>)}</div></section>
    <section className="section split-section"><div><p className="eyebrow">One request, clear next steps</p><h2>Know what’s agreed before work begins.</h2></div><ol className="steps-list"><li><b>Describe the job</b><span>Share the location, timing and what you need done.</span></li><li><b>Compare quotes</b><span>Review scope, schedule and price before you accept.</span></li><li><b>Keep the details together</b><span>Track messages, changes and completion evidence on the job.</span></li></ol></section>
    <section className="provider-callout"><div><p className="eyebrow">For service providers</p><h2>Show your work.<br/>Find your next customer.</h2><p>Build a profile, list what you offer and respond to requests in one workspace.</p><Link className="button button-lime" to="/provider/onboarding">Set up a provider profile <Icon name="arrow"/></Link></div><div className="callout-side"><span>01 / Profile</span><span>02 / Services</span><span>03 / Requests</span></div></section>
  </>;
}


export function Services() {
  const { slug } = useParams();
  const category = categories.find((c) => c.id === slug);
  const visible = useMemo(() => category ? providers.filter((p) => p.services.some((s) => category.services.some((c) => s.toLowerCase().includes(c.toLowerCase()) || c.toLowerCase().includes(s.toLowerCase())))) : [], [category]);
  if (slug && !category) return <NotFound/>;
  if (category) return <><Meta title={`${category.name} in Nigeria`} description={`${category.summary} Search providers and request a quote on Nexthub.`} indexable/><PageIntro eyebrow="Service category" title={category.name} description={category.summary} action={<Link className="button button-dark" to={`/post-a-task?category=${category.id}`}>Post a custom request</Link>}/><section className="section body-section"><div className="service-chips">{category.services.map((service) => <Link className="service-chip" to={`/providers?q=${encodeURIComponent(service)}`} key={service}>{service}<Icon name="arrow"/></Link>)}</div><div className="section-top results-top"><div><p className="eyebrow">People offering related services</p><h2>Browse by profile</h2></div></div><ProviderGrid list={visible}/><p className="small-note">Profiles shown here are examples for the Nexthub demo. Identity checks and marketplace reviews are not connected.</p></section></>;
  return <><Meta title="Browse services" description="Browse home services, repairs, transport, creative work and professional services available across Nigeria." indexable/><PageIntro eyebrow="Open service catalogue" title="Find a service for the work at hand." description="Browse a category, search by the words you use, or post a request when the service is not listed." action={<Link className="button button-dark" to="/post-a-task">Post a task</Link>}/><section className="section body-section"><div className="category-list">{categories.map((c, i) => <Link className="category-row" to={`/services/${c.id}`} key={c.id}><span className="category-index">{String(i + 1).padStart(2, '0')}</span><span><b>{c.name}</b><small>{c.summary}</small></span><span className="row-services">{c.services.slice(0, 3).join(' · ')}</span><Icon name="arrow"/></Link>)}</div><ServiceProposal/></section></>;
}


export function ServiceProposal() {
  const state = useDemoState(); const [value, setValue] = useState(''); const [message, setMessage] = useState('');
  function submit(e: FormEvent) { e.preventDefault(); if (!value.trim()) return; proposeService(value); setMessage(`“${value.trim()}” added to this browser’s demo proposal list.`); setValue(''); }
  return <div className="proposal-box"><div><p className="eyebrow">Catalogue suggestions</p><h2>Can’t find the service?</h2><p>Suggest a name. In a live marketplace, the team would review it before it appears in search.</p></div><form onSubmit={submit}><label htmlFor="proposal">Service name</label><div className="inline-form"><input id="proposal" value={value} onChange={(e) => setValue(e.target.value)} placeholder="e.g. solar inverter repair" required/><button className="button button-dark">Suggest</button></div>{message && <p className="form-success" role="status">{message}</p>}{state.proposals.length > 0 && <small>Suggestions in this demo: {state.proposals.join(', ')}</small>}</form></div>;
}


export function Providers() {
  const [params, setParams] = useSearchParams();
  const [q, setQ] = useState(params.get('q') ?? ''); const [location, setLocation] = useState(params.get('location') ?? '');
  const [category, setCategory] = useState(''); const [availability, setAvailability] = useState(''); const [verified, setVerified] = useState(false); const [business, setBusiness] = useState(''); const [maxPrice, setMaxPrice] = useState(''); const [sort, setSort] = useState('relevant');
  const matches = useMemo(() => {
    const words = q.toLowerCase().trim().split(/\s+/).filter(Boolean);
    return providers.filter((p) => {
      const haystack = `${p.name} ${p.role} ${p.location} ${p.services.join(' ')} ${p.summary} ${p.experience}`.toLowerCase();
      const wordsMatch = words.length === 0 || words.some((word) => haystack.includes(word));
      const locationMatch = !location.trim() || p.location.toLowerCase().includes(location.trim().toLowerCase());
      const categoryMatch = !category || p.services.some((s) => s.toLowerCase().includes(category.toLowerCase()));
      return wordsMatch && locationMatch && categoryMatch && (!availability || p.availability === availability) && (!verified || p.verified) && (!business || p.type === business) && (!maxPrice || p.startingPrice <= Number(maxPrice));
    }).sort((a, b) => sort === 'price' ? a.startingPrice - b.startingPrice : sort === 'name' ? a.name.localeCompare(b.name) : a.location.localeCompare(b.location));
  }, [q, location, category, availability, verified, business, maxPrice, sort]);
  function submit(e: FormEvent) { e.preventDefault(); const p = new URLSearchParams(); if (q) p.set('q', q); if (location) p.set('location', location); setParams(p); }
  return <><Meta title="Find service providers" description="Search provider profiles by service, skill, location, price, availability and business type."/><PageIntro eyebrow="Provider directory" title="Find someone for the job." description="Search the service and area. Refine the list to compare people and businesses." action={<Link className="button button-dark" to="/post-a-task">Post a task instead</Link>}/><section className="section body-section"><form className="discovery-search" onSubmit={submit}><label><span>Service or skill</span><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Try generator repair or WAEC tutor"/></label><label><span>Location</span><input value={location} onChange={(e) => setLocation(e.target.value)} placeholder="Ikeja, Lagos"/></label><button className="button button-dark"><Icon name="search"/> Update results</button></form><div className="discovery-layout"><aside className="filters"><div className="filters-heading"><b>Filters</b><button className="text-button" onClick={() => { setCategory(''); setAvailability(''); setVerified(false); setBusiness(''); setMaxPrice(''); }}>Clear</button></div><label>Service category<select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">All categories</option>{categories.flatMap((c) => c.services).map((s) => <option key={s}>{s}</option>)}</select></label><label>Starting price up to<input type="number" min="0" value={maxPrice} onChange={(e) => setMaxPrice(e.target.value)} placeholder="Any price (₦)"/></label><label>Availability<select value={availability} onChange={(e) => setAvailability(e.target.value)}><option value="">Any time</option><option>Today</option><option>This week</option><option>By arrangement</option></select></label><label>Provider type<select value={business} onChange={(e) => setBusiness(e.target.value)}><option value="">People and businesses</option><option>Individual</option><option>Business</option></select></label><label className="check-control"><input type="checkbox" checked={verified} onChange={(e) => setVerified(e.target.checked)}/> Verified profile</label><small>Demo profiles are not verified, so this filter returns none.</small></aside><div className="results"><div className="results-toolbar"><span><b>{matches.length}</b> profiles <span className="muted">for your search</span></span><label>Sort by <select value={sort} onChange={(e) => setSort(e.target.value)}><option value="relevant">Location</option><option value="price">Lowest starting price</option><option value="name">Name</option></select></label></div><ProviderGrid list={matches}/>{matches.length === 0 && <div className="empty-state"><b>No matching profiles yet.</b><p>Try a nearby area, remove a filter or send a request to the whole marketplace.</p><Link className="button button-dark" to="/post-a-task">Describe the job</Link></div>}</div></div></section></>;
}


export function ProviderProfile() {
  const { id = '' } = useParams(); const p = providers.find((provider) => provider.id === id);
  if (!p) return <NotFound/>;
  return <><Meta title={`${p.name}, ${p.role}`} description={`${p.role} based in ${p.location}. View services and request a quote on Nexthub.`}/><section className="profile-wrap"><Link className="back-link" to="/providers">← Back to providers</Link><div className="profile-head"><div className="avatar avatar-large">{p.name.split(' ').map((w) => w[0]).join('')}</div><div><p className="eyebrow">Example provider profile</p><h1>{p.name}</h1><p className="profile-role">{p.role} · {p.type}</p><p className="provider-details"><span><Icon name="pin"/>{p.location}</span><span>{p.availability}</span></p></div><div className="profile-actions"><Link className="button button-dark" to={`/post-a-task?provider=${p.id}`}>Request a quote</Link><SaveProfile p={p}/></div></div><div className="profile-content"><section><p className="eyebrow">About</p><h2>Work and service details</h2><p>{p.summary}</p><h3>Services offered</h3><div className="service-list">{p.services.map((s) => <div key={s}><span>{s}</span><Link to={`/post-a-task?service=${encodeURIComponent(s)}&provider=${p.id}`}>Ask about this <Icon name="arrow"/></Link></div>)}</div><h3>Experience</h3><p>{p.experience}. Ask for examples relevant to your job before accepting a quote.</p><div className="notice">This example profile has no verified identity, completed-job count or customer ratings. Those trust signals should appear only after checks and completed platform jobs.</div></section><aside className="profile-aside"><b>Before you book</b><p>Share the scope, location and timing. Review the provider’s quote before you agree to the work.</p><Link className="button button-dark button-block" to={`/post-a-task?provider=${p.id}`}>Request a quote</Link></aside></div></section></>;
}

export function SaveProfile({ p }: { p: Provider }) { const state = useDemoState(); const saved = state.saved.includes(p.id); return <button className="button button-light" onClick={() => toggleSaved(p.id)} aria-pressed={saved}>{saved ? 'Saved' : 'Save provider'}</button>; }
