import { useState, type FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { type Role } from '../domain';
import { setRole, useDemoState } from '../store';
import { Icon, Meta, NotFound, PageIntro } from '../components';
import { ServiceProposal } from './Discovery';
import { JobRow } from './Requests';
export function ProviderWorkspace() {
  const state = useDemoState();
  return <><Meta title="Provider workspace" description="Manage service listings, customer requests, quotes, jobs and verification steps."/><PageIntro eyebrow="Provider workspace · Demo" title="Work starts with a clear profile." description="The provider workspace is a preview. Local actions only update this browser." action={<Link className="button button-dark" to="/provider/onboarding">Set up profile</Link>}/><section className="section body-section"><div className="role-switch"><span>Demo role</span>{(['Customer', 'Provider', 'Business', 'Admin'] as Role[]).map((role) => <button className={state.role === role ? 'role-active' : ''} onClick={() => setRole(role)} key={role}>{role}</button>)}</div><div className="workspace-grid"><aside className="workspace-nav"><p>My workspace</p><Link to="/provider">Overview</Link><Link to="/provider/services">Services</Link><Link to="/provider/leads">Leads & quotes</Link><Link to="/provider/jobs">Jobs</Link><Link to="/provider/portfolio">Portfolio</Link><Link to="/provider/verification">Verification</Link><Link to="/provider/earnings">Earnings</Link></aside><div className="workspace-main"><div className="section-top"><div><p className="eyebrow">Requests to review</p><h2>Open work</h2></div><Link className="text-link" to="/provider/leads">All leads <Icon name="arrow"/></Link></div><div className="job-list">{state.jobs.filter((j) => ['REQUESTED', 'QUOTED', 'ACCEPTED', 'IN_PROGRESS', 'PROVIDER_MARKED_COMPLETE', 'DISPUTE'].includes(j.status)).map((j) => <JobRow job={j} key={j.id}/>)}</div><div className="workspace-cards"><Link to="/provider/services"><small>01 / Listings</small><b>Manage services</b><span>Change service details and starting prices</span></Link><Link to="/provider/verification"><small>02 / Trust</small><b>Verification status</b><span>See what checks are available in production</span></Link><Link to="/provider/earnings"><small>03 / Money</small><b>Earnings & payouts</b><span>No real balances are shown in this demo</span></Link></div></div></div></section></>;
}

export function ProviderSection() {
  const { section = '' } = useParams(); const names: Record<string, string> = { services: 'Services', leads: 'Leads & quotes', jobs: 'Jobs', portfolio: 'Portfolio', verification: 'Verification', earnings: 'Earnings & payouts' }; const title = names[section]; const state = useDemoState();
  if (!title) return <NotFound/>;
  return <><Meta title={title} description={`${title} in your Nexthub provider demo workspace.`}/><PageIntro eyebrow="Provider workspace" title={title} description={section === 'verification' ? 'No identity checks run in this demo. Production verification needs an approved provider and secure storage.' : 'This screen shows the intended workspace and sample browser data.'}/><section className="section body-section"><WorkspaceTabs/><div className="panel"><h2>{title}</h2>{section === 'services' ? <><p>Your service listings are stored locally for this demo.</p><ServiceProposal/></> : section === 'verification' ? <div className="verification-list"><p><b>Email</b><span>Not connected</span></p><p><b>Phone</b><span>Not connected</span></p><p><b>Identity</b><span>No check submitted</span></p><p><b>Business</b><span>No documents collected</span></p><p><b>Qualifications</b><span>Add only when relevant to a service</span></p></div> : section === 'earnings' ? <><p>Transactions, platform fees, settlement balances, refunds and payouts are separate records in production.</p><div className="notice">No live balance is available. Do not use this demo to make financial decisions.</div></> : section === 'portfolio' ? <p>No portfolio media has been uploaded. Secure uploads are not enabled.</p> : <div className="job-list">{state.jobs.map((j) => <JobRow job={j} key={j.id}/>)}</div>}</div></section></>;
}

export function WorkspaceTabs() { return <nav className="workspace-tabs" aria-label="Provider sections">{[['/provider', 'Overview'], ['/provider/services', 'Services'], ['/provider/leads', 'Leads'], ['/provider/jobs', 'Jobs'], ['/provider/portfolio', 'Portfolio'], ['/provider/verification', 'Verification'], ['/provider/earnings', 'Earnings']].map(([to, label]) => <Link to={to} key={to}>{label}</Link>)}</nav>; }


export function Onboarding() { const [done, setDone] = useState(false); function submit(e: FormEvent) { e.preventDefault(); setDone(true); } return <><Meta title="Provider profile setup" description="Create a provider profile and add services to the Nexthub open catalogue."/><PageIntro eyebrow="Provider onboarding" title="Set up your service profile." description="Tell customers what you do, where you work and how you price the job."/><section className="section form-section"><form className="form-panel" onSubmit={submit}><label>Profile type<select><option>Individual provider</option><option>Service business</option></select></label><label>Name<input required placeholder="Your name or business name"/></label><label>Services offered<input required placeholder="e.g. plumbing, pump installation"/></label><label>Area covered<input required placeholder="e.g. Ikeja and nearby areas, Lagos"/></label><label>About your work<textarea rows={4} required minLength={20} placeholder="Experience, qualifications, tools and the jobs you take on."/></label><div className="notice">This demo saves no identity documents and grants no verification badge. Never upload government ID to an unconfigured demo.</div><button className="button button-dark button-large">Save profile draft</button>{done && <p className="form-success" role="status">Profile draft captured for this page view. Account creation and publishing need a backend.</p>}</form></section></>; }


export function Business() { return <><Meta title="Business workspace" description="Organize service requests, vendor work and team access for a business."/><PageIntro eyebrow="Business workspace · Preview" title="Keep vendor work in one place." description="Create requests for your team, track quote decisions and keep each job’s scope with its updates." action={<Link className="button button-dark" to="/post-a-task">Request a service</Link>}/><section className="section body-section"><div className="business-intro"><div><p className="eyebrow">Company work</p><h2>Requests, schedules and records</h2><p>Team permissions, invoices and shared company records need an authenticated business account.</p></div><Link className="button button-light" to="/business/team">Business team</Link></div><div className="workspace-cards"><Link to="/jobs"><small>01 / Requests</small><b>Jobs & requests</b><span>Track briefs and quote decisions</span></Link><Link to="/providers"><small>02 / Vendors</small><b>Find a provider</b><span>Search local and remote services</span></Link><Link to="/business/billing"><small>03 / Records</small><b>Billing setup</b><span>Payments are not connected</span></Link></div></section></>; }

export function BusinessTeam() { return <><Meta title="Business team" description="Business team access controls preview."/><PageIntro eyebrow="Business settings" title="Team access" description="A company admin can invite colleagues and set who may create jobs, approve quotes and view billing."/><section className="section body-section"><div className="notice">Invites and permissions are unavailable until account authentication and server-side access control are configured.</div></section></>; }


export function Admin() { const { section } = useParams(); const titles: Record<string, string> = { users: 'Users', services: 'Service catalogue', verification: 'Verification queue', jobs: 'Jobs', payments: 'Payments & payouts', disputes: 'Disputes', reports: 'Reports', audit: 'Audit log', settings: 'Settings' }; const state = useDemoState(); const title = section ? titles[section] : 'Marketplace operations'; return <><Meta title={title || 'Operations'} description="Operations workspace preview for Nexthub marketplace administration."/><PageIntro eyebrow="Admin workspace · Preview" title={title || 'Operations'} description="Example queues only. Administrative actions require verified staff access and a server-side audit record."/><section className="section body-section"><nav className="workspace-tabs" aria-label="Admin sections">{Object.entries(titles).map(([slug, label]) => <Link to={`/admin/${slug}`} key={slug}>{label}</Link>)}</nav>{section === 'jobs' || section === 'disputes' ? <div className="job-list">{state.jobs.filter((job) => section === 'jobs' || job.status === 'DISPUTE').map((j) => <JobRow job={j} key={j.id}/>)}</div> : <div className="panel"><p>{section === 'services' ? 'Providers may propose services; admin review, merge and category assignment are not connected in this demo.' : section === 'verification' ? 'No identity or business documents are held by this demo.' : section === 'payments' ? 'Payment records and payout decisions are not connected.' : section === 'audit' ? 'No privileged actions are available to audit in this browser-only experience.' : section === 'users' ? 'User records and account actions require server-side authorization.' : section === 'reports' ? 'No activity metrics are displayed because this demo has no real marketplace data.' : section === 'settings' ? 'Platform fees and trust policies must be configured server-side.' : 'Open an operations section to review its current demo state.'}</p></div>}</section></>; }
