export type Role = 'Customer' | 'Provider' | 'Business' | 'Admin';
export type JobStatus = 'REQUESTED' | 'QUOTED' | 'ACCEPTED' | 'PAYMENT_PENDING' | 'FUNDED' | 'SCHEDULED' | 'PROVIDER_EN_ROUTE' | 'IN_PROGRESS' | 'PROVIDER_MARKED_COMPLETE' | 'CUSTOMER_CONFIRMATION' | 'COMPLETED' | 'SETTLEMENT_PENDING' | 'SETTLED' | 'DISPUTE';
export interface Category { id: string; name: string; summary: string; services: string[]; }
export interface Provider { id: string; name: string; role: string; location: string; type: 'Individual' | 'Business'; services: string[]; summary: string; startingPrice: number; verified: boolean; experience: string; availability: 'Today' | 'This week' | 'By arrangement'; }
export interface Quote { id: string; providerId: string; amount: number; scope: string; schedule: string; status: 'Sent' | 'Accepted' | 'Declined'; }
export interface Job { id: string; title: string; category: string; description: string; location: string; date: string; budget?: number; providerId?: string; status: JobStatus; quote?: Quote; completionNotes?: string; completionMaterials?: string; receiptDetails?: string; completionSubmittedAt?: string; disputeReason?: string; additionalCharge?: { amount: number; reason: string; status: 'REQUESTED' | 'APPROVED' | 'DECLINED' }; }
export interface DemoState { role: Role; saved: string[]; jobs: Job[]; proposals: string[]; }
export const categories: Category[] = [
  { id: 'home', name: 'Home & cleaning', summary: 'Cleaning, laundry, gardening and household help.', services: ['Home cleaning', 'Laundry', 'Gardening', 'Fumigation', 'Housekeeping'] },
  { id: 'repairs', name: 'Repairs & trades', summary: 'Plumbing, electrical, AC and generator work.', services: ['Plumber', 'Electrician', 'AC repair', 'Generator repair', 'Carpenter', 'Painter', 'Welder'] },
  { id: 'transport', name: 'Drivers & transport', summary: 'Local drivers, airport runs and moving help.', services: ['Driver', 'Airport transfer', 'Moving help', 'Delivery'] },
  { id: 'errands', name: 'Errands & delivery', summary: 'Pickups, shopping and everyday errands.', services: ['Errand runner', 'Personal shopper', 'Document delivery', 'Dispatch'] },
  { id: 'tech', name: 'Technology', summary: 'IT help, websites, apps and business systems.', services: ['IT support', 'Web developer', 'CCTV installation', 'Network setup', 'Phone repair'] },
  { id: 'creative', name: 'Creative & media', summary: 'Design, photography, video and writing.', services: ['Graphic designer', 'Photographer', 'Video editor', 'Writer', 'Product designer'] },
  { id: 'business', name: 'Business & professional', summary: 'Bookkeeping, admin, consulting and specialist work.', services: ['Accountant', 'Virtual assistant', 'Consultant', 'Bookkeeper', 'Research'] },
  { id: 'learning', name: 'Lessons & training', summary: 'Tutors, exam prep and practical training.', services: ['Home tutor', 'WAEC tutor', 'Music teacher', 'Driving instructor'] },
  { id: 'events', name: 'Events & catering', summary: 'Food, planning, styling and event staff.', services: ['Caterer', 'Event planner', 'Decorator', 'DJ', 'MC'] },
  { id: 'beauty', name: 'Beauty & wellness', summary: 'Hair, grooming, fitness and personal care.', services: ['Barber', 'Makeup artist', 'Hair stylist', 'Fitness trainer'] },
  { id: 'auto', name: 'Automotive', summary: 'Mechanics, diagnostics, detailing and towing.', services: ['Mechanic', 'Car diagnostics', 'Auto electrician', 'Towing'] },
  { id: 'other', name: 'Something else', summary: 'Describe the work in your own words.', services: ['Custom request'] },
];
// Example listings only: no ratings, job counts, identity claims, or platform totals.
export const providers: Provider[] = [
  { id: 'chinedu-okafor', name: 'Chinedu Okafor', role: 'Generator & AC technician', location: 'Ikeja, Lagos', type: 'Individual', services: ['Generator repair', 'Generator servicing', 'AC repair', 'Maintenance'], summary: 'Residential and commercial maintenance. Ask for a diagnosis and scope before agreeing a price.', startingPrice: 15000, verified: false, experience: 'Maintenance work', availability: 'Today' },
  { id: 'amaka-bello', name: 'Amaka Bello', role: 'Home cleaner', location: 'Lekki, Lagos', type: 'Individual', services: ['Home cleaning', 'Office cleaning', 'Laundry'], summary: 'Home and office cleaning, with recurring visits available by arrangement.', startingPrice: 12000, verified: false, experience: 'Home and office cleaning', availability: 'This week' },
  { id: 'tunde-adeyemi', name: 'Tunde Adeyemi', role: 'Professional driver', location: 'Yaba, Lagos', type: 'Individual', services: ['Driver', 'Airport transfer', 'Event transport'], summary: 'Local, airport and event transport. Share your route and schedule for a quote.', startingPrice: 10000, verified: false, experience: 'Local and airport transport', availability: 'Today' },
  { id: 'sarah-ibrahim', name: 'Sarah Ibrahim', role: 'Product designer', location: 'Wuse, Abuja', type: 'Individual', services: ['Product designer', 'Web designer', 'Design systems'], summary: 'Product design from early research and wireframes to handoff-ready screens.', startingPrice: 80000, verified: false, experience: 'Digital product design', availability: 'This week' },
  { id: 'musa-lawal', name: 'Musa Lawal', role: 'Plumber & water systems', location: 'Ikeja, Lagos', type: 'Individual', services: ['Plumber', 'Borehole', 'Pump installation'], summary: 'Plumbing repairs and water systems for homes, offices and commercial properties.', startingPrice: 10000, verified: false, experience: 'Plumbing and water systems', availability: 'Today' },
  { id: 'david-eze', name: 'David Eze', role: 'Web developer', location: 'Port Harcourt, Rivers', type: 'Individual', services: ['Web developer', 'Web apps', 'APIs'], summary: 'Web applications and business systems with clear handover notes.', startingPrice: 120000, verified: false, experience: 'Web development', availability: 'This week' },
  { id: 'blessing-adebayo', name: 'Blessing Adebayo', role: 'Event decorator', location: 'Surulere, Lagos', type: 'Individual', services: ['Event decorator', 'Venue styling'], summary: 'Event styling for birthdays, weddings, corporate gatherings and smaller celebrations.', startingPrice: 75000, verified: false, experience: 'Event styling', availability: 'By arrangement' },
  { id: 'emeka-nwosu', name: 'Emeka Nwosu', role: 'CCTV & network specialist', location: 'Gwarinpa, Abuja', type: 'Individual', services: ['CCTV installation', 'Network setup', 'Access control'], summary: 'Security and network installations for homes, offices and growing businesses.', startingPrice: 35000, verified: false, experience: 'CCTV and office networks', availability: 'Today' },
  { id: 'clearline-networks', name: 'Clearline Office Networks', role: 'CCTV & network installation business', location: 'Gwarinpa, Abuja', type: 'Business', services: ['CCTV installation', 'Network setup', 'Access control'], summary: 'Office network and CCTV projects. Share the site size and equipment list for a scoped quote.', startingPrice: 65000, verified: false, experience: 'Office networks and CCTV', availability: 'By arrangement' },
];
export const sampleJobs: Job[] = [
  { id: 'NX-DEMO-1048', title: 'Generator servicing', category: 'Repairs & trades', description: 'Service two generators and report anything that needs repair before replacing parts.', location: 'Ikeja, Lagos', date: '2026-10-05', budget: 35000, providerId: 'chinedu-okafor', status: 'IN_PROGRESS' },
  { id: 'NX-DEMO-1042', title: 'Apartment deep cleaning', category: 'Home & cleaning', description: 'Deep clean a two-bedroom apartment.', location: 'Lekki, Lagos', date: '2026-10-07', budget: 25000, providerId: 'amaka-bello', status: 'ACCEPTED' },
  { id: 'NX-DEMO-NEW', title: 'CCTV installation', category: 'Technology', description: 'Demo completion scenario: CCTV installation in a small office. Review the provider’s submitted work before confirming.', location: 'Gwarinpa, Abuja', date: '2026-10-12', budget: 180000, providerId: 'emeka-nwosu', status: 'PROVIDER_MARKED_COMPLETE', completionNotes: 'Installation finished. Please inspect the evidence before deciding whether to confirm.' },
];
export const formatNaira = (amount: number) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 }).format(amount);
